name: rest_json_testing
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  async_loader: "^0.1.1"
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
